// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/forget-password": {
    params: {};
  };
  "/new-password": {
    params: {};
  };
  "/profile": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/forget-password" | "/new-password" | "/profile" | "/dashboard";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/forget-password.tsx": {
    id: "routes/forget-password";
    page: "/forget-password";
  };
  "routes/new-password.tsx": {
    id: "routes/new-password";
    page: "/new-password";
  };
  "routes/profile.tsx": {
    id: "routes/profile";
    page: "/profile";
  };
  "routes/dashboard.tsx": {
    id: "routes/dashboard";
    page: "/dashboard";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/forget-password": typeof import("./app/routes/forget-password.tsx");
  "routes/new-password": typeof import("./app/routes/new-password.tsx");
  "routes/profile": typeof import("./app/routes/profile.tsx");
  "routes/dashboard": typeof import("./app/routes/dashboard.tsx");
};